const { createHash } = require('crypto');

 // Creating a string hash!

 function hash(input) {
   return createHash('sha256').update(input).digest('base64');
 }

// Compare two hashed passwords!
let password = 'Hello, Protogen-primordial-test!';
const hash1 = hash(password);
console.log(hash1)

//A few hours later.

password = 'Hello, Protogen-primordial-test!';
const hash2 = hash(password);
const match = hash1 === hash2;

console.log(match ? '✔️ Good Password' : ' ❌ Wrong Password, do not match!');

//But this is not Secure as hash generated by this will using the same encrypting method and
//and anyone with a basic rainbow-table can can decrypt this!
